export enum CharactersActionTypes {
  GET_CHARACTERS = "GET_CHARACTERS",
  GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS",
  GET_CHARACTERS_ERROR = "GET_CHARACTERS_ERROR",
  GET_EYE_COLORS_SUCCESS = "GET_EYE_COLORS_SUCCESS",
  GET_GENDERS_SUCCESS = "GET_GENDERS_SUCCESS",
}